### ISSUE TITLE
Command with combinations of find is not working.

### ISSUE THREAD

**Issue by bdarksider** [aChatir/MongoExec#10]
In your code you are calling toArray on commands with find in them. But it results in error when using commands like db.collectionName.findOne()

**Comment by aChatir** [comment]
Hello there:
I've added a fix. could you check from your side. and let me know if there any issue.
Thanks for your reporting.

**Comment by bdarksider** [comment]
Thanks. db.collectionName.findOne() works fine now.
But with current implementation db.collectionName.find().count() fail

**Comment by aChatir** [comment]
Hello there it's seems ok now. could you test from your side
Thank you.

**Comment by bejoygm** [comment]
It works fine now. Thanks
