### ISSUE TITLE
can not exec aggergate function

### ISSUE THREAD

**Issue by kioyong** [aChatir/MongoExec#11]
db.tableName.aggregate([]) exec success,
db.tableName.aggregate([{$project:{_id:1}}]) throw SyntaxError

**Comment by aChatir** [comment]
Hello there:
I've tested your cases and they work fine for me. could you check the console after executing the command and paste here the result from the console. so I could check why?
Thank you.

**Comment by bdarksider** [comment]
I've tested the cases and it works fine.

**Comment by aChatir** [comment]
Thank you for your reporting
