### ISSUE TITLE
display find() not working (but findOne is working well)

### ISSUE THREAD

**Issue by BejaouiSayf** [aChatir/MongoExec#12]
[issue_find()_query_not_working_in_MongoExec_Sublime_text.txt](https://github.com/aChatir/MongoExec/files/2221439/issue_find._query_not_working_in_MongoExec_Sublime_text.txt)

**Comment by aChatir** [comment]
Hi,
Could you open the console of ST and paste here the log?
if there some screen-shot it will help a lot
Thank you for the report
