### ISSUE TITLE
How does one change the connection

### ISSUE THREAD

**Issue by hendrikswan** [aChatir/MongoExec#5]
Hi,

I'm very intrigued by this project! I tried to use it, and it worked well enough against one connection. 
I set up a different connection, but now I'm unsure of how to execute my commands against a particular connection. 

I've tried going through list connections, and then selecting the connection that I want to query, but then it lists the dbs from another connection. 

In summary: How does one go about changing the active connection?

Thanks
Hendrik

**Comment by aChatir** [comment]
Hi,
+ How does one go about changing the active connection?

here is a copy of my setting : 
```json
{
    "mongo_exec.commands": {
        "mongo" : "/usr/bin/mongo"
    },
    "connections": {
        "Localhost": {
            "type"    : "mongo",
            "host"    : "localhost",
            "port"    : "27017",
            "username": "",
            "password": "",
            "databases": ""
        },
        "Staging": {
            "type"    : "mongo",
            "host"    : "serverNameOrAddress",
            "port"    : "27017",
            "username": "",
            "password": "",
            "databases": ""
        }
    }
}
```
chnage the serverNameOrAddress by your server address also the port if you need other one.
so if you want to change your connection just redo the combination of Ctrl + Alt + w and choose the new server. all command will execute to the new server choosen.
 Note : if there any issue. any suggestion fill free to ask.

Thanks.
Abdelaziz.

**Comment by hendrikswan** [comment]
Hi Abdelaziz,

Thanks for replying to my question.
I do have different connections set up, same as you.
Let's say I'm connected to connection A, and running my commands
successfully against connection A.
When I Ctrl + Alt + w to select a different connection, it does bring up
both connections. I then select a different connection (connection B), but
then the plugin lists the databases for connection A.
So I understand how it's supposed to work, but it does not behave
accordingly.

Thanks
Hendrik

**Comment by hendrikswan** [comment]
I am on a mac, does that help?

**Comment by aChatir** [comment]
I'll do more test an let you now about the progress.
Thanks.

**Comment by aChatir** [comment]
If you can do the flowing will help: 
From your sublime open the console and run **Ctrl + Alt + w** and paste the log  here. 
Thanks.

**Comment by hendrikswan** [comment]
Ah man! That allowed me to debug it better. I was being stupid, and had the wrong host name for my second connection.

Sorry for wasting your time!
