### ISSUE TITLE
Not working on Win10

### ISSUE THREAD

**Issue by nokios** [aChatir/MongoExec#6]
Trying to utilize this plugin on a local instance.. it gives me the following error.

> 'C:\Program' is not recognized as an internal or external command, operable program or batch file.

Below is my configuration

```
{
	"mongo_exec.commands": {
		"mongo": "C:\\Program Files\\MongoDB\\Server\\3.2\\bin\\mongo.exe"
	},
	"connections": {
		"localhost": {
			"type": "mongo",
			"host": "localhost",
			"port": "27017",
			"username": "",
			"password": "",
			"databases": ""
		}
	}
}
```

This is the console output:

```
>>> 
C:\Program Files\MongoDB\Server\3.2\bin\mongo.exe localhost:27017/localhost --eval "printjson(db.getMongo().getDBNames())"
[]
C:\Program Files\MongoDB\Server\3.2\bin\mongo.exe localhost:27017/localhost --eval "printjson(db.getMongo().getDBNames())"
[]
Traceback (most recent call last):
  File "MongoExec in C:\Users\Trenton\AppData\Roaming\Sublime Text 3\Installed Packages\MongoExec.sublime-package", line 190, in mongoChangeDB
IndexError: list index out of range
```

**Comment by aChatir** [comment]
Hi nokios:
I've added a fix for this could you test again and let me know if still exists.
Note: the sublime package well be updated in 1 hour, so check here https://packagecontrol.io/packages/MongoExec the  Last Seen time.
Thanks for your report.

**Comment by nokios** [comment]
Will try today as I can. Thanks for the quick response. I didn't even bother to look at the code, or I would have maybe submitted a pull request. :). Will let you know the result today, hopefully.

**Comment by nokios** [comment]
I am able to run mongoexec now.  thanks!

**Comment by aChatir** [comment]
no worries. thanks for your report
