### ISSUE TITLE
executing the current file

### ISSUE THREAD

**Issue by MatteoSp** [aChatir/MongoExec#7]
You should add a command (or an option) to simply executing the current file

**Comment by aChatir** [comment]
Hi MatteoSp:
I guess this is already exists. open new tab in Sublime and write you command(s) 
Like so : 
     db.mycollection.find()
     db.mycollection.help()
and put the cursor above the command that you want to execute and do the combination of : 
Ctrl+w Ctrl+w
if this not what you suggest could you explain to me more about your feature. 
thank's and you are welcome for any suggestions or improvement.

**Comment by MatteoSp** [comment]
Hi, 
I'd like to execute something like this:

`var items = db.myCollection.find();
items.forEach(function(item) {
    print(item._id);
});`

**Comment by aChatir** [comment]
Hi MatteoSp:
Thank you for you suggestion.  I want to tell you that I've added this feature to the plug-in. 
so enjoy it and thanks again.

**Comment by MatteoSp** [comment]
thanks aChatir, what about just executing the current file?

**Comment by aChatir** [comment]
Hi MatteoSp:
hmmmm. I've thought about that but  there is a use case that might be an issue if the file not yet saved. in this case we can't get a full path for the file. that's why I've added it like that. but I'll do research of how to execute it from the same file if not yet saved. I'll let you know about that.
Thanks.

**Comment by MatteoSp** [comment]
You could just generate a random file name, save it in the TEMP folder, and run it.

**Comment by aChatir** [comment]
I've thought also for that, however there might be some issues with permissions. especially from *inux machines. but I'll tried it since I have linux os and we will see. 
Thanks

**Comment by aChatir** [comment]
Hi MatteoSp:
good news I've added teh ability to execute it from the active view. so even the file is not yet saved we can execute it. you can test, use the combination of Ctrl+w Ctrl+v. if you have a windows or mac system could you test it if it work. tested with linux system and it work perfectly.
Thanks again.

**Comment by MatteoSp** [comment]
Super! I confirm it works on Windows. Thanks!
