### ISSUE TITLE
Path /usr/bin/mongo doesn't work 

### ISSUE THREAD

**Issue by akhileshmohan** [aChatir/MongoExec#9]
I'm new to sublime text and mongo and wondering what's the correct path. Please let me know how to derive the path (for mac OS X) that I need to mention in the mongoexce settings. Thanks

**Comment by aChatir** [comment]
use this command to get get the right path:
`$ which mongo`
this will show you something like this /usr/bin/mongo
so will use this as path from the settings
this is t-he default settings
`{
    "mongo_exec.commands": {
        "mongo" : "/usr/bin/mongo"
    },
    "connections": {
        "Localhost": {
            "type"    : "mongo",
            "host"    : "localhost",
            "port"    : "27017",
            "username": "",
            "password": "",
            "databases": ""
        }
    }
}`

I hope this will help you.

**Comment by akhileshmohan** [comment]
Perfect...found the path...Thank you @aChatir

**Comment by aChatir** [comment]
I am glad that this fix the issue.
